apiVersion: v1
kind: Service
metadata:
  name: t3transaction
  labels:
    app: t3transaction
spec:
  ports:
    - port: 30004
      name: http
  selector:
    app: t3transaction
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: svc-transaction
  labels:
    account: SVC_TRANSACTION
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: t3transaction
  labels:
    app: t3transaction
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: t3transaction
      version: v1
  template:
    metadata:
      name: transaction-pod
      labels:
        app: t3transaction
        version: v1
    spec:
      serviceAccountName: svc-transaction
      containers:
        - name: transaction
          image: docker.io/coultonf/t3transaction:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 30004
          livenessProbe:
            httpGet:
              path: /api/v1/transaction/health
              port: 30004
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /api/v1/transaction/readiness
              port: 30004
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 5
